In [1]:
import numpy as np
import tensorflow as tf
import pandas as pd
import matplotlib.pyplot as plt

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)

In [2]:
# deal with age lable
train_raw = pd.read_csv("train.csv")
for i in range(891):
    if np.isnan(train_raw.iloc[i,5]):
        if "Miss" in train_raw.iloc[i,3]:
            train_raw.iloc[i,5] = 10
        if "Master" in train_raw.iloc[i,3]:
            train_raw.iloc[i,5] = 4
        else:
            train_raw.iloc[i,5] = 30

In [11]:
# save to csv
train_raw.to_csv('train_age.csv')

train_age = pd.read_csv('train_age.csv')
tmp = pd.read_csv("train_1.csv")

tmp['Age'] = train_age.iloc[:,6]
tmp = tmp.drop(columns=['SibSp','Parch'])
tmp.to_csv('train_3.csv')

In [9]:
# deal with test sets

test_raw = pd.read_csv("test.csv")
for i in range(418):
    if np.isnan(test_raw.iloc[i,4]):
        if "Miss" in test_raw.iloc[i,2]:
            test_raw.iloc[i,4] = 10
        if "Master" in test_raw.iloc[i,2]:
            test_raw.iloc[i,4] = 4
        else:
            test_raw.iloc[i,4] = 30

# save to csv

tmp = pd.read_csv("test_1.csv")
tmp['Age'] = test_raw.iloc[:,4]
tmp = tmp.drop(columns=['SibSp','Parch'])
tmp.to_csv("test_3.csv")

     PassengerId  Pclass  Sex      Fare  Embarked   Age
0            892       3    0    7.8292         1  34.5
1            893       3    1    7.0000         0  47.0
2            894       2    0    9.6875         1  62.0
3            895       3    0    8.6625         0  27.0
4            896       3    1   12.2875         0  22.0
5            897       3    0    9.2250         0  14.0
6            898       3    1    7.6292         1  30.0
7            899       2    0   29.0000         0  26.0
8            900       3    1    7.2292         2  18.0
9            901       3    0   24.1500         0  21.0
10           902       3    0    7.8958         0  30.0
11           903       1    0   26.0000         0  46.0
12           904       1    1   82.2667         0  23.0
13           905       2    0   26.0000         0  63.0
14           906       1    1   61.1750         0  47.0
15           907       2    1   27.7208         2  24.0
16           908       2    0   12.3500         1  35.0
17           909       3    0    7.2250         2  21.0
18           910       3    1    7.9250         0  27.0
19           911       3    1    7.2250         2  45.0
20           912       1    0   59.4000         2  55.0
21           913       3    0    3.1708         0   9.0
22           914       1    1   31.6833         0  30.0
23           915       1    0   61.3792         2  21.0
24           916       1    1  262.3750         2  48.0
25           917       3    0   14.5000         0  50.0
26           918       1    1   61.9792         2  22.0
27           919       3    0    7.2250         2  22.5
28           920       1    0   30.5000         0  41.0
29           921       3    0   21.6792         2  30.0
..           ...     ...  ...       ...       ...   ...
388         1280       3    0    7.7500         1  21.0
389         1281       3    0   21.0750         0   6.0
390         1282       1    0   93.5000         0  23.0
391         1283       1    1   39.4000         0  51.0
392         1284       3    0   20.2500         0  13.0
393         1285       2    0   10.5000         0  47.0
394         1286       3    0   22.0250         0  29.0
395         1287       1    1   60.0000         0  18.0
396         1288       3    0    7.2500         1  24.0
397         1289       1    1   79.2000         2  48.0
398         1290       3    0    7.7750         0  22.0
399         1291       3    0    7.7333         1  31.0
400         1292       1    1  164.8667         0  30.0
401         1293       2    0   21.0000         0  38.0
402         1294       1    1   59.4000         2  22.0
403         1295       1    0   47.1000         0  17.0
404         1296       1    0   27.7208         2  43.0
405         1297       2    0   13.8625         2  20.0
406         1298       2    0   10.5000         0  23.0
407         1299       1    0  211.5000         2  50.0
408         1300       3    1    7.7208         1  30.0
409         1301       3    1   13.7750         0   3.0
410         1302       3    1    7.7500         1  30.0
411         1303       1    1   90.0000         1  37.0
412         1304       3    1    7.7750         0  28.0
413         1305       3    0    8.0500         0  30.0
414         1306       1    1  108.9000         2  39.0
415         1307       3    0    7.2500         0  38.5
416         1308       3    0    8.0500         0  30.0
417         1309       3    0   22.3583         2   4.0

[418 rows x 6 columns]